
spring:
  datasource:
    url: jdbc:mariadb://localhost:3308/befriends
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: nt6819
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: true
  profiles:
    active: local
    include: jwt
server:
  port: 8081
