
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: true
server:
  port: 8081
