cloud:
  aws:
    s3:
      bucket: ${{secrets.S3_BUCKET}}
    stack.auto: false
    region.static: ${{secrets.S3_REGION}}
    credentials:
      accessKey: ${{secrets.S3_ACCESS_KEY}}
      secretKey: ${{secrets.S3_SECRET_KEY}}

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${{secrets.DATASOURCE_URL}}
    username: ${{secrets.DATASOURCE_USERNAME}}
    password: ${{secrets.DATASOURCE_PASSWORD}}
  jpa:
    hibernate:
      ddl-auto: update