cloud:
  aws:
    s3:
      bucket: befriends
    credentials:
      access-key: AKIATPKWOWPTZJB5ZA4G
      secret-key: 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
    region:
      static: ap-northeast-2
    stack:
      auto: false
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  datasource:
    url: jdbc:mariadb://befriends-backend.cgeoa5gu9cm5.ap-northeast-2.rds.amazonaws.com:3306/befriends_backend
    driver-class-name: org.mariadb.jdbc.Driver
    username: admin
    password: nt406819
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: true
server:
  port: 8081